service: labby-time
provider:
  name: aws
  runtime: go1.x
package:
 exclude:
   - ./**
 include:
   - ./bin/**
functions:
  lambda-time:
    handler: bin/labby-time
    events:
      - http:
          path: /
